require("user/options")
require("user/keymaps")
require("user/plugins")
require("user/colorscheme")
require("user/statusline")
require("user/cmp")
require("user/lsp")
require("user/treesitter")
require("user/nvimtree")

